version: "3"
services: 
    redis-cluster-6380:
        image: redis:5.0.5-alpine
        container_name: node-80
        ports:
            - "6380:6380"
        volumes:
            - ./conf/redis-6380.conf:/usr/local/etc/redis/redis.conf
            - ./log:/var/log/redis
            - ./data:/data/redis
        command: sh -c "redis-server /usr/local/etc/redis/redis.conf"

    redis-cluster-6381:
        image: redis:5.0.5-alpine
        container_name: node-81
        ports:
            - "6381:6381"
        volumes:
            - ./conf/redis-6381.conf:/usr/local/etc/redis/redis.conf
            - ./log:/var/log/redis
            - ./data:/data/redis
        command: sh -c "redis-server /usr/local/etc/redis/redis.conf"

    redis-cluster-6382:
        image: redis:5.0.5-alpine
        container_name: node-82
        ports:
            - "6382:6382"
        volumes:
            - ./conf/redis-6382.conf:/usr/local/etc/redis/redis.conf
            - ./log:/var/log/redis
            - ./data:/data/redis
        command: sh -c "redis-server /usr/local/etc/redis/redis.conf"

    redis-cluster-6383:
        image: redis:5.0.5-alpine
        container_name: node-83
        ports:
            - "6383:6383"
        volumes:
            - ./conf/redis-6383.conf:/usr/local/etc/redis/redis.conf
            - ./log:/var/log/redis
            - ./data:/data/redis
        command: sh -c "redis-server /usr/local/etc/redis/redis.conf"

    redis-cluster-6384:
        image: redis:5.0.5-alpine
        container_name: node-84
        ports:
            - "6384:6384"
        volumes:
            - ./conf/redis-6384.conf:/usr/local/etc/redis/redis.conf
            - ./log:/var/log/redis
            - ./data:/data/redis
        command: sh -c "redis-server /usr/local/etc/redis/redis.conf"

    redis-cluster-6385:
        image: redis:5.0.5-alpine
        container_name: node-85
        ports:
            - "6385:6385"
        volumes:
            - ./conf/redis-6385.conf:/usr/local/etc/redis/redis.conf
            - ./log:/var/log/redis
            - ./data:/data/redis
        command: sh -c "redis-server /usr/local/etc/redis/redis.conf"
